const LANG_KEY = 'whs_lang';

const translations = {
  es: {
    loading: 'Cargando...',
    login_tagline:   'Comprobantes en la nube',
    login_btn:       'Iniciar sesión con Google',
    login_hint:      'Tus presets se sincronizan en todos tus dispositivos',
    active_profile:  'Perfil activo',
    no_profile:      'Sin perfil',
    saved_presets:   'Presets guardados',
    new_preset_btn:  '+ Nuevo preset',
    signout:         'Salir',
    preview_btn:     '👁 Vista previa',
    print:           '🖨\u00A0 Imprimir / PDF',
    save_png:        '🖼\u00A0 Guardar PNG',
    save_pdf:        '📄\u00A0 Guardar PDF',
    switch_profile:  '👤\u00A0 Cambiar perfil',
    light_mode:      'Modo claro',
    dark_mode:       'Modo oscuro',
    profile_modal_title: 'Perfiles de comprobante',
    profile_modal_hint:  'Cada perfil tiene sus propios presets guardados de forma independiente.',
    new_profile_placeholder: 'Nombre del nuevo perfil',
    create_profile_btn: '+ Crear',
    no_presets_select_profile: 'Seleccioná un perfil para ver los presets.',
    no_presets_saved:          'Sin presets guardados',
    section_01: 'Datos del Servicio',
    section_02: 'Datos del Cliente',
    section_03: 'Detalles del Servicio',
    section_04: 'Información de Pago',
    section_05: 'Firma Digital',
    lbl_service_name:   'Nombre del servicio',
    lbl_frequency:      'Frecuencia (MHz)',
    lbl_website:        'Sitio Web',
    lbl_address:        'Dirección',
    lbl_phone:          'Teléfono',
    lbl_email:          'Correo Electrónico',
    lbl_watermark:      'Marca de Agua',
    lbl_watermark_hint: '(dejar vacío para no mostrar)',
    ph_service_name:  'Ej: Servicio de Streaming',
    ph_frequency:     '(Opcional) Ej: 105.1 Mhz',
    ph_website:       'Ej: www.google.com',
    ph_address:       'Ej: Av. Siempre Viva 123',
    ph_phone:         'Ej: 3735404142',
    ph_email:         'Ej: contacto@tuempresa.com.ar',
    ph_watermark:     'Ej: FM Amistad 105.1 MHz',
    lbl_client_name:    'Nombre o Razón Social',
    lbl_client_address: 'Dirección',
    ph_client_name:     'Ej: Panadería El Trigo',
    ph_client_address:  'Ej: Av. Siempre Viva 123',
    lbl_billing_date: 'Fecha de cobro (MM-AAAA)',
    lbl_reason:       'Razón de Cobro',
    lbl_amount:       'Monto ($ ARS)',
    ph_billing_date:  '01-2026',
    ph_reason:        'Ej: Servicio de Streaming',
    ph_amount:        '10000',
    lbl_alias:        'Alias',
    ph_alias:         'E: mialias123',
    lbl_qr:           'Imagen del QR de pago',
    lbl_qr_hint:      '(se guarda en el preset)',
    qr_drop_text:     'Arrastrá tu QR aquí o',
    qr_drop_link:     'seleccioná un archivo',
    qr_drop_hint:     'PNG, JPG — se guarda en el preset',
    qr_loaded:        '✅ QR cargado',
    remove_qr:        '✕ Quitar',
    sig_hint:         'El fondo se elimina automáticamente, dejando solo la firma visible en el comprobante.',
    lbl_sig:          'Imagen de la firma',
    sig_drop_text:    'Arrastrá la firma aquí o',
    sig_drop_link:    'seleccioná un archivo',
    sig_drop_hint:    'PNG, JPG — se eliminará el fondo automáticamente',
    sig_loaded:       '✅ Firma cargada',
    sig_processing:   '⏳ Procesando...',
    remove_sig:       '✕ Quitar',
    lbl_preset_name:  'Nombre del Preset',
    ph_preset_name:   'Ej: Panadería El Trigo',
    save_preset:      '💾 Guardar preset',
    delete_preset:    '🗑 Eliminar preset',
    saving:           '⏳ Guardando...',
    saved:            '✅ Guardado',
    deleted:          '✅ Eliminado',
    error_saving:     '❌ Error',
    confirm_title:    'Confirmar acción',
    confirm_cancel:   'Cancelar',
    confirm_delete:   'Eliminar',
    alert_select_profile:    'Por favor seleccioná o creá un perfil primero.',
    alert_preset_name:       'Por favor ingresá un nombre para el preset.',
    alert_preset_too_long:   'El nombre no puede exceder 100 caracteres.',
    alert_warnings_prefix:   'Advertencias:\n',
    alert_warnings_suffix:   '\n\n¿Deseas guardar igualmente?',
    alert_error_profile:     'Error al crear el perfil.',
    alert_error_delete_prof: 'Error al eliminar el perfil.',
    alert_error_delete_pre:  'Error al eliminar el preset.',
    alert_login_error:       'Error al iniciar sesión: ',
    alert_png_error:         'Error al generar PNG.',
    alert_pdf_error:         'Error al generar PDF.',
    val_service_required:    'El nombre del servicio es requerido',
    val_amount_invalid:      'El monto debe ser un número',
    err_profile_name:        'Por favor ingresá un nombre.',
    err_profile_max:         'Máximo 100 caracteres.',
    err_profile_exists:      'Ya existe un perfil con este nombre.',
    err_loading_profiles:    'Error cargando perfiles.',
    no_profiles_yet:         'No tenés perfiles todavía. Creá uno abajo.',
    confirm_delete_profile:  '¿Eliminar el perfil "{name}"? Se borrarán todos sus presets.',
    confirm_delete_preset:   '¿Eliminar este preset? Esta acción no se puede deshacer.',
    confirm_delete_title:    'Eliminar perfil',
    confirm_delete_pre_title:'Eliminar preset',
    inv_client_section:  'Datos del Cliente',
    inv_service_section: 'Detalles del Servicio',
    inv_name_label:      'Nombre o Razón Social:',
    inv_address_label:   'Dirección:',
    inv_date_label:      'Fecha de cobro:',
    inv_desc_col:        'Descripción',
    inv_amount_col:      'Monto ($ ARS)',
    inv_total:           'TOTAL: $',
    inv_firma_label:     'Firma:',
    inv_dir:             'Dir:',
    inv_tel:             'Tel:',
    inv_no_qr:           'Sin QR',
  },

  en: {
    loading: 'Loading...',
    login_tagline:   'Receipts in the cloud',
    login_btn:       'Sign in with Google',
    login_hint:      'Your presets sync across all your devices',
    active_profile:  'Active profile',
    no_profile:      'No profile',
    saved_presets:   'Saved presets',
    new_preset_btn:  '+ New preset',
    signout:         'Sign out',
    preview_btn:     '👁 Preview',
    print:           '🖨\u00A0 Print / PDF',
    save_png:        '🖼\u00A0 Save PNG',
    save_pdf:        '📄\u00A0 Save PDF',
    switch_profile:  '👤\u00A0 Switch profile',
    light_mode:      'Light mode',
    dark_mode:       'Dark mode',
    profile_modal_title: 'Receipt profiles',
    profile_modal_hint:  'Each profile has its own independently saved presets.',
    new_profile_placeholder: 'New profile name',
    create_profile_btn: '+ Create',
    no_presets_select_profile: 'Select a profile to see its presets.',
    no_presets_saved:          'No saved presets',
    section_01: 'Service Information',
    section_02: 'Client Information',
    section_03: 'Service Details',
    section_04: 'Payment Information',
    section_05: 'Digital Signature',
    lbl_service_name:   'Service name',
    lbl_frequency:      'Frequency (MHz)',
    lbl_website:        'Website',
    lbl_address:        'Address',
    lbl_phone:          'Phone',
    lbl_email:          'Email',
    lbl_watermark:      'Watermark',
    lbl_watermark_hint: '(leave empty to hide)',
    ph_service_name:  'Ex: Streaming Service',
    ph_frequency:     '(Optional) Ex: 105.1 MHz',
    ph_website:       'Ex: www.google.com',
    ph_address:       'Ex: 123 Main St',
    ph_phone:         'Ex: 3735404142',
    ph_email:         'Ex: contact@yourcompany.com',
    ph_watermark:     'Ex: FM Friendship 105.1 MHz',
    lbl_client_name:    'Name or Company',
    lbl_client_address: 'Address',
    ph_client_name:     'Ex: The Wheat Bakery',
    ph_client_address:  'Ex: 123 Main St',
    lbl_billing_date: 'Billing date (MM-YYYY)',
    lbl_reason:       'Billing reason',
    lbl_amount:       'Amount ($ ARS)',
    ph_billing_date:  '01-2026',
    ph_reason:        'Ex: Streaming Service',
    ph_amount:        '10000',
    lbl_alias:        'Alias',
    ph_alias:         'Ex: myalias123',
    lbl_qr:           'Payment QR image',
    lbl_qr_hint:      '(saved in preset)',
    qr_drop_text:     'Drag your QR here or',
    qr_drop_link:     'select a file',
    qr_drop_hint:     'PNG, JPG — saved in preset',
    qr_loaded:        '✅ QR loaded',
    remove_qr:        '✕ Remove',
    sig_hint:         'The background is automatically removed, leaving only the signature visible on the receipt.',
    lbl_sig:          'Signature image',
    sig_drop_text:    'Drag your signature here or',
    sig_drop_link:    'select a file',
    sig_drop_hint:    'PNG, JPG — background will be removed automatically',
    sig_loaded:       '✅ Signature loaded',
    sig_processing:   '⏳ Processing...',
    remove_sig:       '✕ Remove',
    lbl_preset_name:  'Preset name',
    ph_preset_name:   'Ex: The Wheat Bakery',
    save_preset:      '💾 Save preset',
    delete_preset:    '🗑 Delete preset',
    saving:           '⏳ Saving...',
    saved:            '✅ Saved',
    deleted:          '✅ Deleted',
    error_saving:     '❌ Error',
    confirm_title:    'Confirm action',
    confirm_cancel:   'Cancel',
    confirm_delete:   'Delete',
    alert_select_profile:    'Please select or create a profile first.',
    alert_preset_name:       'Please enter a name for the preset.',
    alert_preset_too_long:   'Name cannot exceed 100 characters.',
    alert_warnings_prefix:   'Warnings:\n',
    alert_warnings_suffix:   '\n\nSave anyway?',
    alert_error_profile:     'Error creating profile.',
    alert_error_delete_prof: 'Error deleting profile.',
    alert_error_delete_pre:  'Error deleting preset.',
    alert_login_error:       'Login error: ',
    alert_png_error:         'Error generating PNG.',
    alert_pdf_error:         'Error generating PDF.',
    val_service_required:    'Service name is required',
    val_amount_invalid:      'Amount must be a number',
    err_profile_name:        'Please enter a name.',
    err_profile_max:         'Maximum 100 characters.',
    err_profile_exists:      'A profile with this name already exists.',
    err_loading_profiles:    'Error loading profiles.',
    no_profiles_yet:         'No profiles yet. Create one below.',
    confirm_delete_profile:  'Delete profile "{name}"? All its presets will be removed.',
    confirm_delete_preset:   'Delete this preset? This action cannot be undone.',
    confirm_delete_title:    'Delete profile',
    confirm_delete_pre_title:'Delete preset',
    inv_client_section:  'Client Information',
    inv_service_section: 'Service Details',
    inv_name_label:      'Name or Company:',
    inv_address_label:   'Address:',
    inv_date_label:      'Billing date:',
    inv_desc_col:        'Description',
    inv_amount_col:      'Amount ($ ARS)',
    inv_total:           'TOTAL: $',
    inv_firma_label:     'Signature:',
    inv_dir:             'Addr:',
    inv_tel:             'Tel:',
    inv_no_qr:           'No QR',
  }
};

let currentLang = localStorage.getItem(LANG_KEY) || 'es';

function t(key) {
  return (translations[currentLang] && translations[currentLang][key])
    || translations['es'][key]
    || key;
}

function setLang(lang) {
  currentLang = lang;
  localStorage.setItem(LANG_KEY, lang);
  applyTranslations();
  updateLangToggle();
}

function applyTranslations() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    el.textContent = t(key);
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    el.placeholder = t(el.dataset.i18nPh);
  });
  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    el.title = t(el.dataset.i18nTitle);
  });
}

function updateLangToggle() {
  const btn = document.getElementById('btnLangToggle');
  if (btn) btn.textContent = currentLang === 'es' ? '🌐 English' : '🌐 Español';
}